apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nfs-server
spec:
  selector:
    matchLabels:
      app: nfs-server # Label selector that determines which Pods belong to the StatefulSet
  serviceName: "nfs-server"
  replicas: 1
  template:
    metadata:
      labels:
        app: nfs-server # Pod template's label selector
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: nfs-server
        image: gcr.io/google_containers/volume-nfs:0.8
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /exports
            name: nfs-pvc
  volumeClaimTemplates:
  - metadata:
      name: nfs-pvc
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
